### ISSUE TITLE
Bug sum of game hours per user

### ISSUE THREAD

**Issue by IvanQA2** [IvanQA2/javaQaDiplom#2]
# Описание
Не суммируется накопленное время игры пользователя

# Локация дефекта
https://github.com/IvanQA2/javaQaDiplom/blob/6b96589bce3d9d0f34a1a9f0b027ccb815e7db01/src/main/java/ru/netology/GameStore.java#L46
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/IvanQA2/javaQaDiplom/blob/main/src/main/java/ru/netology/GameStore.java#L46) в IDEA
1. Запустить тест
1. Посмотреть на результат

*Ожидаемый результат:* Вывод сообщения: **Тест пройден**
*Фактический результат:* Вывод сообщения: **Тест не пройден**

# Скриншот
![image](https://raw.githubusercontent.com/IvanQA2/javaQaDiplom/gamestore/Screen.png)

# Окружение

* **Операционная система:** macOS Ventura версия 13.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by AlessioLoginov** [comment]
исправлено
