### ISSUE TITLE
Bug sum of game hours of all users

### ISSUE THREAD

**Issue by IvanQA2** [IvanQA2/javaQaDiplom#3]
# Описание
Не суммируется время игры всех пользователей

# Локация дефекта
https://github.com/IvanQA2/javaQaDiplom/blob/fcc73ba661565569f870443e740ff9e67f1cc184/src/main/java/ru/netology/GameStore.java#L77
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/IvanQA2/javaQaDiplom/blob/main/src/main/java/ru/netology/GameStore.java#L46) в IDEA
1. Запустить тест
1. Посмотреть на результат

*Ожидаемый результат:* Вывод сообщения: **Тест пройден**
*Фактический результат:* Вывод сообщения: **Тест не пройден**

# Скриншот
![image](https://raw.githubusercontent.com/IvanQA2/javaQaDiplom/gamestore/screen1.png)

# Окружение

* **Операционная система:** macOS Ventura версия 13.1
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by AlessioLoginov** [comment]
исправлено
