### ISSUE TITLE
Метод mostPlayerByGenre всегда возвращает значение null

### ISSUE THREAD

**Issue by AlessioLoginov** [IvanQA2/javaQaDiplom#5]
# Описание
Метод mostPlayerByGenre выдает null при валидных и не валидных значениях

# Локация дефекта
https://github.com/IvanQA2/javaQaDiplom/blob/6b96589bce3d9d0f34a1a9f0b027ccb815e7db01/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IvanQA2/javaQaDiplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Добавить игроку player игру game
3. Добавить игроку player время проигранное в игру game 3 часа
4. Вызвать тест метода mostPlayerByGenre для game

*Ожидаемый результат:* Тест должен пройти и показать правильный результат
*Фактический результат:* При любых запросах этого метода actual = null

# Скриншот
![Без названия (3)](https://user-images.githubusercontent.com/112719436/213883705-135318a9-e9b5-419f-bde5-368c08678a9b.png)

#Окружение
Операционная система: MacOS Monterey 12.6.2
IDE: IntelliJ IDEA 2022.2.3 (Community Edition)
Java: OpenJDK 11

**Comment by AlessioLoginov** [comment]
upd screen

**Comment by AlessioLoginov** [comment]
upd

**Comment by IvanQA2** [comment]
bug fixed
