### ISSUE TITLE
В методе sumGenre при использовании отрицательного значения времени, результат отрицательный, а должен быть 0

### ISSUE THREAD

**Issue by AlessioLoginov** [IvanQA2/javaQaDiplom#6]
# Описание
В методе sumGenre при использовании не валидного значения времени, результат не валидный, а должен быть 0

# Локация дефекта
https://github.com/IvanQA2/javaQaDiplom/blob/6b96589bce3d9d0f34a1a9f0b027ccb815e7db01/src/main/java/ru/netology/Player.java#L45

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IvanQA2/javaQaDiplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Добавить игроку player игру game
3. Добавить игроку player время проигранное в игру game -5 часов
4. Запустить тест

*Ожидаемый результат:* Тест должен пройти, expected = actual = 0
*Фактический результат:* Тест не прошел, вышла ошибка, expected = 0, actual = -5

# Скриншот
![Без названия (4)](https://user-images.githubusercontent.com/112719436/213883917-8968a348-03e2-4425-a6d1-344fa310ca68.png)

#Окружение
Операционная система: MacOS Monterey 12.6.2
IDE: IntelliJ IDEA 2022.2.3 (Community Edition)
Java: OpenJDK 11

**Comment by IvanQA2** [comment]
bug fixed
