### ISSUE TITLE
Не суммируется время, если игрок играет в одну игру несколько раз

### ISSUE THREAD

**Issue by AlessioLoginov** [IvanQA2/javaQaDiplom#7]
# Описание
При добавлении игроку времени одной игры несколько раз, время не суммируется.

# Локация дефекта
https://github.com/IvanQA2/javaQaDiplom/blob/6b96589bce3d9d0f34a1a9f0b027ccb815e7db01/src/main/java/ru/netology/Player.java#L45

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IvanQA2/javaQaDiplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Добавить игроку player игру game
3. Добавить игроку player время проигранное в игру game 4 часа
4. Добавить игроку player время проигранное в игру game 3 часа
Запустить тест

*Ожидаемый результат:* Тест должен пройти, expected = actual = 7
*Фактический результат:* Вышла ошибка, expected = 7, actual = 0

# Скриншот
![Без названия (5)](https://user-images.githubusercontent.com/112719436/213884337-f525c025-b63c-4cb9-a1a1-3912c08824f6.png)

#Окружение
Операционная система: MacOS Monterey 12.6.2
IDE: IntelliJ IDEA 2022.2.3 (Community Edition)
Java: OpenJDK 11

**Comment by IvanQA2** [comment]
bug fixed
