### ISSUE TITLE
Не генерируется RuntimeException, если игра не была установлена

### ISSUE THREAD

**Issue by AlessioLoginov** [IvanQA2/javaQaDiplom#8]
# Описание
Если игра не была установлена, то тест проходит, а не генерирует RuntimeException как сказано в условии задачи

# Локация дефекта
https://github.com/IvanQA2/javaQaDiplom/blob/6b96589bce3d9d0f34a1a9f0b027ccb815e7db01/src/main/java/ru/netology/Player.java#L34

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IvanQA2/javaQaDiplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Добавить игроку player время проигранное в игру game 3 часа
3. Запустить тест

*Ожидаемый результат:* Тест не проходит, выкидывает RuntimeException
*Фактический результат:* Тест проходит

# Скриншот
![Без названия (6)](https://user-images.githubusercontent.com/112719436/213884728-9de0f490-38ae-4e06-beb2-17b4ec362a72.png)

#Окружение
Операционная система: MacOS Monterey 12.6.2
IDE: IntelliJ IDEA 2022.2.3 (Community Edition)
Java: OpenJDK 11

**Comment by IvanQA2** [comment]
bug fixed
